unity_dir = join_paths(theme_dir, 'unity')

install_subdir(
  'window-buttons',
  install_dir: unity_dir,
  strip_directory: true,
)

install_subdir(
  'dash-buttons',
  install_dir: unity_dir,
  strip_directory: true,
)

install_subdir(
  'launcher',
  install_dir: unity_dir,
  strip_directory: true,
)

install_data(
  'dash-widgets.json',
  install_dir: unity_dir,
)
