#!/usr/bin/env bash
set -euo pipefail

input="${1:-${HOME}/.cache/wal/colors.scss}"
output="${2:-src/_color_theme.scss}"

declare -A colors=(
  [background]="#f8fafc"
  [foreground]="#1f2937"
  [cursor]="#2563eb"
  [color0]="#f8fafc"
  [color1]="#e5e7eb"
  [color2]="#d1d5db"
  [color3]="#9ca3af"
  [color4]="#2563eb"
  [color5]="#7c3aed"
  [color6]="#0891b2"
  [color7]="#1f2937"
  [color8]="#6b7280"
  [color9]="#dc2626"
  [color10]="#16a34a"
  [color11]="#ca8a04"
  [color12]="#1d4ed8"
  [color13]="#9333ea"
  [color14]="#0e7490"
  [color15]="#111827"
)

if [[ -f "$input" ]]; then
  while IFS= read -r line; do
    if [[ "$line" =~ ^\$([a-zA-Z0-9_]+):[[:space:]]*(#[0-9a-fA-F]{6}) ]]; then
      colors["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
    fi
  done < "$input"
fi

colors[foreground]="${colors[color8]}"
colors[cursor]="${colors[color0]}"

{
  printf '%s\n' '// Generated by scripts/generate-color-theme.sh.'
  printf '%s\n\n' '// Edit the generator input, not this file.'
  for name in background foreground cursor color0 color1 color2 color3 color4 color5 color6 color7 color8 color9 color10 color11 color12 color13 color14 color15; do
    printf '$%s: %s !default;\n' "$name" "${colors[$name]}"
  done
} > "$output"

printf 'Generated %s' "$output"
if [[ -f "$input" ]]; then
  printf ' from %s' "$input"
fi
printf '\n'
