#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND, nvidia-drm
env = NVD_BACKEND=direct

env = XCURSOR_SIZE,16
env = XCURSOR_THEME,whiteglass
env = HYPRCURSOR_SIZE,16
env = HYPRCURSOR_THEME,whiteglass

