background = 0xFF0A0502
base = 0xFFCD7505
alternate_base = 0xFFf5e9a2
text = 0xFFf5e9a2
bright_text = 0xFFB9890E
accent = 0xFFFCCA0C
accent_secondary = 0xFFDE9306
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = ""
font_family = "Sans Serif"
font_family_monospace = "monospace"
