background = 0xFF000910
base = 0xFF036E8F
alternate_base = 0xFFa7d9e9
text = 0xFFa7d9e9
bright_text = 0xFF027398
accent = 0xFF048CB1
accent_secondary = 0xFF7497a3
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = ""
font_family = "Sans Serif"
font_family_monospace = "monospace"
