background = 0xFF000018
base = 0xFFAD0C2C
alternate_base = 0xFFe5dfe2
text = 0xFFe5dfe2
bright_text = 0xFFB61D42
accent = 0xFFA57688
accent_secondary = 0xFFa09c9e
h1_size = 19
h2_size = 15
h3_size = 13
font_size = 11
small_font_size = 10
icon_theme = ""
font_family = "Sans Serif"
font_family_monospace = "monospace"
