##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = float yes, match:class appscratcheditor
windowrule = min_size 1000 600, float yes, match:class org.pulseaudio.pavucontrol
windowrule = float yes, match:class qalculate-gtk
windowrule = float yes, match:class hyprpwcenter
windowrule = float yes, match:class appchangewal
windowrule = float yes, match:class hyprwal
windowrule = float yes, match:class vlc 
