--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexin/Wallpapers/fav/a_red_sun_over_mountains.jpg"

-- Special
background="#101116"
foreground="#9abdb8"
cursor="#9abdb8"

-- Colors
color0="#101116"
color1="#A03D3A"
color2="#DC392F"
color3="#E23C31"
color4="#E14235"
color5="#3E827C"
color6="#4D877A"
color7="#9abdb8"
color8="#6b8480"
color9="#A03D3A"
color10="#DC392F"
color11="#E23C31"
color12="#E14235"
color13="#3E827C"
color14="#4D877A"
color15="#9abdb8"
