# Shell variables
# Generated by 'wal'
wallpaper='/home/alexin/Wallpapers/trees-8451483_1920.jpg'

# Special
background='#0d1924'
foreground='#dec89d'
cursor='#dec89d'

# Colors
color0='#0d1924'
color1='#53696B'
color2='#6D726D'
color3='#9B773D'
color4='#90765F'
color5='#758770'
color6='#9A8D63'
color7='#dec89d'
color8='#9b8c6d'
color9='#53696B'
color10='#6D726D'
color11='#9B773D'
color12='#90765F'
color13='#758770'
color14='#9A8D63'
color15='#dec89d'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
