--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexin/Pictures/a_planet_in_space_with_clouds.jpg"

-- Special
background="#000101"
foreground="#77cbe0"
cursor="#77cbe0"

-- Colors
color0="#000101"
color1="#00637C"
color2="#00718E"
color3="#017FA0"
color4="#01809F"
color5="#018CB0"
color6="#009CC4"
color7="#77cbe0"
color8="#538e9c"
color9="#00637C"
color10="#00718E"
color11="#017FA0"
color12="#01809F"
color13="#018CB0"
color14="#009CC4"
color15="#77cbe0"
