# Shell variables
# Generated by 'wal'
wallpaper='/home/alexin/Wallpapers/coffee-5447420_1920.jpg'

# Special
background='#0b0604'
foreground='#cabdc3'
cursor='#cabdc3'

# Colors
color0='#0b0604'
color1='#6B5561'
color2='#8B4E35'
color3='#8C605C'
color4='#8C6B72'
color5='#827183'
color6='#927887'
color7='#cabdc3'
color8='#8d8488'
color9='#6B5561'
color10='#8B4E35'
color11='#8C605C'
color12='#8C6B72'
color13='#827183'
color14='#927887'
color15='#cabdc3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
