--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/alexin/Wallpapers/trees-8451483_1920.jpg"

-- Special
background="#0d1924"
foreground="#dec89d"
cursor="#dec89d"

-- Colors
color0="#0d1924"
color1="#53696B"
color2="#6D726D"
color3="#9B773D"
color4="#90765F"
color5="#758770"
color6="#9A8D63"
color7="#dec89d"
color8="#9b8c6d"
color9="#53696B"
color10="#6D726D"
color11="#9B773D"
color12="#90765F"
color13="#758770"
color14="#9A8D63"
color15="#dec89d"
