# Shell variables
# Generated by 'wal'
wallpaper='/home/alexin/Pictures/a_planet_in_space_with_clouds.jpg'

# Special
background='#000101'
foreground='#77cbe0'
cursor='#77cbe0'

# Colors
color0='#000101'
color1='#00637C'
color2='#00718E'
color3='#017FA0'
color4='#01809F'
color5='#018CB0'
color6='#009CC4'
color7='#77cbe0'
color8='#538e9c'
color9='#00637C'
color10='#00718E'
color11='#017FA0'
color12='#01809F'
color13='#018CB0'
color14='#009CC4'
color15='#77cbe0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
